# Generated by Django 2.0.3 on 2018-07-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=345)),
                ('rating', models.IntegerField()),
                ('img', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('specify', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
