# Generated by Django 2.0.3 on 2018-07-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpkart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products1',
        ),
    ]
