# Generated by Django 2.0.3 on 2018-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpkart', '0002_auto_20180713_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
