# Generated by Django 2.0.3 on 2018-07-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpkart', '0005_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
