# Generated by Django 2.0.7 on 2018-07-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpkart', '0008_cart_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=300)),
                ('userid', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
