# Generated by Django 2.0.7 on 2018-07-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpkart', '0009_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='des',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
